require("codeium").setup({
  config = function()
    vim.keymap.set("i", "<C-;>", function()
      return vim.fn["codeium#Accept"]()
    end, { expr = true, silent = true, noremap = true })
    vim.keymap.set("i", "<c-,>", function()
      return vim.fn["codeium#CycleCompletions"](1)
    end, { expr = true, silent = true, noremap = true })
    vim.keymap.set("i", "<c-.>", function()
      return vim.fn["codeium#CycleCompletions"](-1)
    end, { expr = true, silent = true, noremap = true })
    vim.keymap.set("i", "<c-'>", function()
      return vim.fn["codeium#Clear"]()
    end, { expr = true, silent = true, noremap = true })
    vim.api.nvim_create_user_command("CodeiumChat", function(opts)
      vim.fn["codeium#Chat"]()
    end, { nargs = "*", desc = "Codeium Chat" })
  end,
})
