# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  pkgs,
  lib,
  ...
}: {
  # Enable OpenGL
  hardware.graphics = {
    enable = true;
  };

  environment.systemPackages = [pkgs.lshw pkgs.lshw-gui];

  # Load nvidia driver for Xorg and Wayland
  services.xserver.videoDrivers = ["nvidia"];

  hardware.nvidia = {
    # Modesetting is required.
    modesetting.enable = true;

    # Nvidia power management. Experimental, and can cause sleep/suspend to fail.
    # Enable this if you have graphical corruption issues or application crashes after waking
    # up from sleep. This fixes it by saving the entire VRAM memory to /tmp/ instead
    # of just the bare essentials.
    powerManagement.enable = false;

    # Fine-grained power management. Turns off GPU when not in use.
    # Experimental and only works on modern Nvidia GPUs (Turing or newer).
    powerManagement.finegrained = false;

    # Use the NVidia open source kernel module (not to be confused with the
    # independent third-party "nouveau" open source driver).
    # Support is limited to the Turing and later architectures. Full list of
    # supported GPUs is at:
    # https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus
    # Only available from driver 515.43.04+
    # Currently alpha-quality/buggy, so false is currently the recommended setting.
    open = true;

    # Enable the Nvidia settings menu,
    # accessible via `nvidia-settings`.
    nvidiaSettings = true;

    prime = {
      intelBusId = "PCI:0:2:0";
      nvidiaBusId = "PCI:1:0:0";
      #amdgpuBusId = "PCI:54:0:0"; # If you have an AMD iGPU
      sync.enable = true;
    };

    # Optionally, you may need to select the appropriate driver version for your specific GPU.
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  specialisation.nvidia-PRIME-offload.configuration = {
    system.nixos.tags = ["nvidia-PRIME-offload-best-battery"];
    hardware.nvidia.prime = {
      offload = {
        enable = lib.mkForce true;
        enableOffloadCmd = lib.mkForce true;
      };
      sync.enable = lib.mkForce false;
      reverseSync.enable = lib.mkForce false;
    };
  };

  specialisation.nvidia-PRIME-sync.configuration = {
    system.nixos.tags = ["nvidia-PRIME-sync-best-performance"];
    hardware.nvidia.prime = {
      offload = {
        enable = lib.mkForce false;
        enableOffloadCmd = lib.mkForce false;
      };
      sync.enable = lib.mkForce true;
      reverseSync.enable = lib.mkForce false;
    };
  };

  specialisation.nvidia-PRIME-reverse-sync.configuration = {
    system.nixos.tags = ["nvidia-PRIME-reverse-sync-EXPERIMENTAL"];
    hardware.nvidia.prime = {
      offload = {
        enable = lib.mkForce false;
        enableOffloadCmd = lib.mkForce false;
      };
      sync.enable = lib.mkForce false;
      reverseSync.enable = lib.mkForce true;
    };
  };
}
